### ISSUE TITLE
Discussion: Mode argument instead of flags

### ISSUE THREAD

**Issue by vauhochzett** [glad-dev/dn#2]
Flags suggest that multiple can be combined – which they can't. 
Would it be reasonable to instead use a single "mode argument", e.g.:

```
$ dn t
2022-12-19
 * example
$ dn e
```

Of course, that would either require to add a mode argument for adding notes (which may be suboptimal), or to have two binaries with different names for adding notes vs. editing / viewing etc. Curious to hear your thoughts!

**Comment by glad-dev** [comment]
Initially, the tool used mode arguments since I prefer them as well. The reason I switched to flags is simplicity.

Splitting the add-note functionality into a separate program would complicate the tool's installation since `go install https://github.com/glad-dev/dn@latest` would no longer work.
Additionally, a separate program for adding notes can be simulated with a mode argument using an alias, e.g.:
```bash
alias dna="dn a"
``` 

Thus, the decision is between creating a mode argument for adding notes and misusing flags.
While I agree that mode arguments are easier to understand than flags, I am unsure if they are easier to use, since it requires more typing. What is your opinion?

**Comment by vauhochzett** [comment]
That's fair. I think either option has disadvantages for sure. Alternatively, all modes _except_ adding could be guarded with a separate binary. So `dn test` adds "test", `dnx v` views. Not ideal either, though.

Maybe, one could try to be "smart" about it, e.g.:
1. If only a single argument is provided, check if it is a valid mode argument. If not, add a note, if yes, activate that mode. Disadvantage: Typos in a mode argument would not be noticed by the user, instead a note would be added.
2. Only add a note if at least three letters are entered. For two letters or less, assume a mode argument.

Just meant for the discussion, not sure this even makes sense. What do you think?

p.s. Fun fact, at least on my machine, `go install https://github.com/glad-dev/dn@latest` does not work anyways, instead I need to omit "https://": `go install github.com/glad-dev/dn@latest`

**Comment by glad-dev** [comment]
> p.s. Fun fact, at least on my machine, go install https://github.com/glad-dev/dn@latest does not work anyways, instead I need to omit "https://": go install github.com/glad-dev/dn@latest

You're right, the "https://" does not belong in the `go install` command.
My point was that I am unsure if `go install` can install multiple programs from a single repo.

<hr>

Regarding your suggestions:
> If only a single argument is provided, check if it is a valid mode argument. If not, add a note, if yes, activate that mode. Disadvantage: Typos in a mode argument would not be noticed by the user, instead a note would be added.

An additional disadvantage of this approach is that a user would be prevented from adding notes that are valid flags, e.g. `dn et` would open vim instead of adding "et" to a note. I know that this is an edge case, but it still doesn't sit right with me.

> Only add a note if at least three letters are entered. For two letters or less, assume a mode argument.

This would prevent adding notes that are less than three letters.

<hr>

What do you think of the following idea:
1. If the program receives one argument and said argument is longer than three letters, then the argument is added to a note
2. If the program receives one argument and said argument is shorter than three letters, the program interprets it as a mode
3. In order to add notes that are less than three letters a mode argument must be used

Example:
- `dn Example` adds "Example" to today's note
- `dn et` interprets "et" as mode argument and opens vim
- `dn as` interprets "as" as mode argument and fails since "as" is not a valid mode argument
- `dn a as` adds "as"  to today's note

**Comment by glad-dev** [comment]
I've added an implementation for the proposed solution. It is at the [feature/modes branch](https://github.com/glad-dev/dn/tree/feature/modes).

**Comment by vauhochzett** [comment]
I like that, as it allows the user to explicitly add a short note (even though it is an edge case for sure). I think this behavior should be surfaced via an error message, though. Specifically in case < 3 letters are entered that are not a valid mode; e.g.:

```
$ dn go
fatal: 'go' is not a valid mode.
Arguments of less than three letters are interpreted as modes. To add a short note, use 'dn -a "go"'
```

Furthermore, I noticed that you changed the version flag to be lowercase again (`-v`) – I think capitalizing it is actually quite common, not just if there is a flag conflict; but let me know if you know different.

**Comment by glad-dev** [comment]
> Furthermore, I noticed that you changed the version flag to be lowercase again (-v) – I think capitalizing it is actually quite common, not just if there is a flag conflict; but let me know if you know different.

There is no flag conflict, I switched the flags because prefer lowercase flags. I've seen mixed usage of lowercase and uppercase version flags. Nevertheless, I reverted the version flag to "-V" to keep it consistent.

>  I think this behavior should be surfaced via an error message, though. Specifically in case < 3 letters are entered that are not a valid mode
I've added the error message you suggested, thank you for your input!
